spring.datasource.url=jdbc:postgresql://db.nyexexbblqelnwuhbuhc.supabase.co:5432/postgres?sslmode=require

spring.datasource.username=postgres

spring.datasource.password=Fn@10428550

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082
